javax:
  persistence:
    chema-generation:
      database:
        action: create
    jdbc:
      url: jdbc:ucanaccess://test.accdb
      driver: net.ucanaccess.jdbc.UcanaccessDriver

hibernate:
  cache:
    provider_class: org.hibernate.cache.NoCacheProvider

dataSourceClassName: com.zaxxer.hikari.HikariDataSource
datasource:
  driverClassName: net.ucanaccess.jdbc.UcanaccessDriver
  url: jdbc:ucanaccess://./test.accsb


spring:
  datasource:
    driverClassName: net.ucanaccess.jdbc.UcanaccessDriver
    url: jdbc:ucanaccess://./test.accsb
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 10000
  jpa:
    hibernate:
      naming:
        physical-strategy: com.examples.access.jpa.config.AccessPhysicalNamingStrategy
      temp:
        use_jdbc_metadata_defaults: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.HSQLDialect
